version: '3'

services:
  nginx:
      image: nginx:1.11.10-alpine
      ports:
        - 80:80
      volumes:
        - ./:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
        - showredis-network
  php:
    build: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    networks:
      - showredis-network
  redis:
      image: 'redis:alpine'
      networks:
        - showredis-network

networks:
  showredis-network:
    driver: bridge